name: student-performance-api
region: oregon
services:
- name: api
  type: web
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: python main.py
  plan: starter
  envVars:
  - key: MODEL_PATH
    value: student_model.pkl
  - key: PYTHONUNBUFFERED
    value: "1"
  - key: PYTHONPATH
    value: "."
  - key: WORKERS
    value: "1"
