name: student-performance-api
region: oregon
services:
- name: api
  type: web
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app -w 1 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120 --access-logfile - --error-logfile -
  plan: starter
  envVars:
  - key: MODEL_PATH
    value: student_model.pkl
  - key: PYTHONUNBUFFERED
    value: "1"
  - key: PYTHONPATH
    value: "."
  - key: WORKERS
    value: "1"
